# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3faf75ac57dd87f50cf6ec37bf7496082b75f3cdc0ce23bdf5152db4bbd5218d6c8db34009d64a41f6aa4ddc30b979d1743fd946f75cca82af30a396102acdbb

test:
  secret_key_base: 749c9b9ed68a4ee4fbdcc8d8658c7dd781436f31aa6b36371c569c37702f0d89fab60743f8d52a2a78fe1ea5140c7efe5bb2040261f1c3d3c0f605ff65dfa0c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
